ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.ctfp.plugins.HttpKt.configureHttp
      com.ctfp.plugins.MonitoringKt.configureMonitoring
      com.ctfp.plugins.SerializationKt.configureSerialization
      com.ctfp.plugins.SecurityKt.configureSecurity
      com.ctfp.plugins.AutoHeadResponseKt.configureAutoHeadResponse
      com.ctfp.plugins.RequestValidationKt.configureRequestValidation
      com.ctfp.plugins.ResourcesKt.configureResources
      com.ctfp.plugins.SseKt.configureSse
      com.ctfp.plugins.StatusPagesKt.configureStatusPages
      com.ctfp.plugins.KoinKt.configureKoin
      com.ctfp.plugins.ExposedKt.configureExposed
      com.ctfp.plugins.PostgresKt.configurePostgres
      com.ctfp.plugins.RateLimitingKt.configureRateLimiting
      com.ctfp.plugins.NetworkKt.configureNetwork
      com.ctfp.plugins.NetworkTlsKt.configureNetworkTls
      com.ctfp.plugins.RoutingKt.configureRouting
    ]
  }
}

jwt {
  domain = "https://jwt-provider-domain/"
  audience = "jwt-audience"
  realm = "ktor sample app"
  secret = "secret"
}

postgres {
  url = "jdbc:postgresql://localhost:5432/ctfp"
  user = "ctfp"
  password = "ctfp"
}

kind = Application
