ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [
            com.ctfp.HttpKt.configureHttp
            com.ctfp.MonitoringKt.configureMonitoring
            com.ctfp.SerializationKt.configureSerialization
            com.ctfp.SecurityKt.configureSecurity
            com.ctfp.AutoHeadResponseKt.configureAutoHeadResponse
            com.ctfp.RequestValidationKt.configureRequestValidation
            com.ctfp.ResourcesKt.configureResources
            com.ctfp.SseKt.configureSse
            com.ctfp.StatusPagesKt.configureStatusPages
            com.ctfp.DIKt.configureDependencyInjection
            com.ctfp.KoinKt.configureKoin
            com.ctfp.ExposedKt.configureExposed
            com.ctfp.PostgresKt.configurePostgres
            com.ctfp.RateLimitingKt.configureRateLimiting
            com.ctfp.NetworkKt.configureNetwork
            com.ctfp.NetworkTlsKt.configureNetworkTls
            com.ctfp.WebsocketsKt.configureWebsockets
            com.ctfp.RoutingKt.configureRouting
        ]
    }
}
jwt {
  domain = "https://jwt-provider-domain/"
  audience = "jwt-audience"
  realm = "ktor sample app"
}
postgres {
  url = "jdbc:postgresql://localhost:5432/ctfp"
  user = "ctfp"
  password = "ctfp"
}

kind = Application
