CREATE TABLE IF NOT EXISTS challenge (id SERIAL PRIMARY KEY, title VARCHAR(255) NOT NULL, description TEXT NULL, is_visible BOOLEAN DEFAULT TRUE NOT NULL, publish_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, max_attempts INT NOT NULL, categories TEXT[] NOT NULL, time_limit INT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);
ALTER TABLE challenge ADD CONSTRAINT challenge_title_unique UNIQUE (title);
CREATE SEQUENCE IF NOT EXISTS challenge_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
